name: Deploy
on: workflow_dispatch
jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/rails-lambda/lamby-benchmark-devcontainer
          cacheFrom: ghcr.io/rails-lambda/lamby-benchmark-devcontainer
          runCmd: echo DONE!
  deploy:
    runs-on: ubuntu-latest
    needs: image
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ./vendor/bundle
            ./node_modules
          key: ${{ runner.os }}-deploy-v1-${{ hashFiles('Gemfile.lock', 'yarn.lock') }}
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::589405201853:role/oidc-role-github
          role-duration-seconds: 900
          role-session-name: lamby-benchmark
      - name: Deploy
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/lamby-benchmark-devcontainer
          env: |
            CI
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_SESSION_TOKEN
            AWS_DEFAULT_REGION
            AWS_REGION
          runCmd: |
            ./bin/deploy
