name: Test
on: [push]
jobs:
  image:
    name: Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/rails-lambda/lamby-benchmark-devcontainer
          cacheFrom: ghcr.io/rails-lambda/lamby-benchmark-devcontainer
          runCmd: echo DONE!
  test:
    needs: image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ./vendor/bundle
            ./node_modules
          key: ${{ runner.os }}-test-v1-${{ hashFiles('Gemfile.lock', 'yarn.lock') }}
      - name: Setup & Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/lamby-benchmark-devcontainer
          env: |
            CI
          runCmd: |
            ./bin/setup
            ./bin/test
